package qrcode_test

import (
	"bytes"
	"testing"

	"table-tennis-backend/internal/infrastructure/qrcode"
)

func TestGoQRCodeGenerator_Generate(t *testing.T) {
	gen := qrcode.NewGoQRCodeGenerator()
	if gen == nil {
		t.Fatal("expected NewGoQRCodeGenerator to return non-nil instance")
	}

	data := "https://example.com/test-qr"
	size := 256

	pngBytes, err := gen.Generate(data, size)
	if err != nil {
		t.Fatalf("unexpected error generating QR code: %v", err)
	}

	if len(pngBytes) == 0 {
		t.Fatal("expected non-empty byte slice for QR code")
	}

	// PNG magic header check: \x89PNG\r\n\x1a\n
	pngHeader := []byte{0x89, 'P', 'N', 'G', '\r', '\n', 0x1a, '\n'}
	if !bytes.HasPrefix(pngBytes, pngHeader) {
		t.Error("expected generated bytes to start with PNG magic header")
	}
}

func TestGoQRCodeGenerator_Generate_DataTooLong(t *testing.T) {
	gen := qrcode.NewGoQRCodeGenerator()
	// Data exceeding QR capacity should return error
	largeData := string(make([]byte, 10000))
	_, err := gen.Generate(largeData, 256)
	if err == nil {
		t.Error("expected error when generating QR code with oversized data")
	}
}
