package pdf_test

import (
	"bytes"
	"testing"
	"time"

	"table-tennis-backend/internal/domain/division"
	"table-tennis-backend/internal/domain/event"
	"table-tennis-backend/internal/domain/player"
	"table-tennis-backend/internal/domain/tournament"
	"table-tennis-backend/internal/infrastructure/pdf"
)

func TestGoFpdfGenerator_GenerateTournamentReport(t *testing.T) {
	gen := pdf.NewGoFpdfGenerator()
	if gen == nil {
		t.Fatal("expected NewGoFpdfGenerator to return non-nil instance")
	}

	p1 := &player.Player{ID: "p1", FirstName: "John", LastName: "Doe", Gender: "M", SinglesElo: 1500}
	p2 := &player.Player{ID: "p2", FirstName: "Jane", LastName: "Smith", Gender: "F", SinglesElo: 1400}
	p3 := &player.Player{ID: "p3", FirstName: "Bob", LastName: "Johnson", Gender: "M", SinglesElo: 1300}
	p4 := &player.Player{ID: "p4", FirstName: "Alice", LastName: "Williams", Gender: "F", SinglesElo: 1200}

	maxElo1500 := int16(1500)
	div1 := &division.Division{
		ID:       "div1",
		Name:     "Division 1",
		MinElo:   1000,
		MaxElo:   &maxElo1500,
		Category: "singles",
	}

	ev := &event.Event{
		ID:           "e1",
		Name:         "Championship 2026",
		Type:         "singles",
		Format:       "groups_elimination",
		Status:       "finished",
		StartDate:    time.Now(),
		Participants: []*player.Player{p1, p2, p3, p4},
		Groups: []event.Group{
			{
				ID:      "g1",
				Name:    "Group A",
				Players: []*player.Player{p1, p2},
			},
			{
				ID:      "g2",
				Name:    "Group B",
				Players: []*player.Player{p3, p4},
			},
		},
		Matches: []event.Match{
			{
				ID:         "m1",
				Stage:      "group",
				Status:     "finished",
				TeamA:      []*player.Player{p1},
				TeamB:      []*player.Player{p2},
				WinnerTeam: "A",
				Sets: []event.MatchSet{
					{Number: 1, ScoreA: 11, ScoreB: 8},
					{Number: 2, ScoreA: 11, ScoreB: 9},
					{Number: 3, ScoreA: 11, ScoreB: 5},
				},
			},
			{
				ID:         "m2",
				Stage:      "final",
				Status:     "finished",
				DivisionID: "div1",
				TeamA:      []*player.Player{p1},
				TeamB:      []*player.Player{p3},
				WinnerTeam: "A",
				Sets: []event.MatchSet{
					{Number: 1, ScoreA: 11, ScoreB: 9},
					{Number: 2, ScoreA: 11, ScoreB: 7},
					{Number: 3, ScoreA: 11, ScoreB: 8},
				},
			},
		},
		Metrics: &event.TournamentMetrics{
			TotalMatchesPlayed: 2,
			TotalSetsPlayed:    6,
			TotalPointsScored:  100,
		},
	}

	pdfBytes, err := gen.GenerateTournamentReport(ev, []*division.Division{div1})
	if err != nil {
		t.Fatalf("unexpected error generating tournament report: %v", err)
	}

	if len(pdfBytes) == 0 {
		t.Fatal("expected non-empty byte slice for PDF report")
	}

	if !bytes.HasPrefix(pdfBytes, []byte("%PDF")) {
		t.Error("expected generated bytes to start with %PDF header")
	}
}

func TestGoFpdfGenerator_GenerateEventReport(t *testing.T) {
	gen := pdf.NewGoFpdfGenerator()

	p1 := &player.Player{ID: "p1", FirstName: "Player", LastName: "One", Gender: "M", SinglesElo: 1500}
	p2 := &player.Player{ID: "p2", FirstName: "Player", LastName: "Two", Gender: "M", SinglesElo: 1400}
	p3 := &player.Player{ID: "p3", FirstName: "Player", LastName: "Three", Gender: "M", SinglesElo: 1400}
	p4 := &player.Player{ID: "p4", FirstName: "Player", LastName: "Four", Gender: "M", SinglesElo: 1400}

	ev1 := &event.Event{
		ID:           "e1",
		Name:         "Sub Event 1",
		Type:         "singles",
		Format:       "round_robin",
		Status:       "finished",
		Participants: []*player.Player{p1, p2},
	}

	ev2 := &event.Event{
		ID:           "e2",
		Name:         "Elimination Event",
		Type:         "doubles",
		Format:       "elimination",
		Status:       "finished",
		Participants: []*player.Player{p1, p2, p3, p4},
		Matches: []event.Match{
			{
				ID:         "m_r32",
				Stage:      "r32",
				Status:     "finished",
				TeamA:      []*player.Player{p1, p2},
				TeamB:      []*player.Player{p3, p4},
				WinnerTeam: "A",
				Sets: []event.MatchSet{
					{Number: 1, ScoreA: 11, ScoreB: 5},
				},
			},
			{
				ID:         "m_r16",
				Stage:      "r16",
				Status:     "finished",
				TeamA:      []*player.Player{p1, p2},
				TeamB:      []*player.Player{p3, p4},
				WinnerTeam: "B",
				Sets: []event.MatchSet{
					{Number: 1, ScoreA: 11, ScoreB: 5},
				},
			},
			{
				ID:         "m_qf",
				Stage:      "quarterfinal",
				Status:     "finished",
				TeamA:      []*player.Player{p1, p2},
				TeamB:      []*player.Player{p3, p4},
				WinnerTeam: "A",
				Sets: []event.MatchSet{
					{Number: 1, ScoreA: 11, ScoreB: 5},
				},
			},
			{
				ID:         "m_sf",
				Stage:      "semifinal",
				Status:     "finished",
				TeamA:      []*player.Player{p1, p2},
				TeamB:      []*player.Player{p3, p4},
				WinnerTeam: "A",
				Sets: []event.MatchSet{
					{Number: 1, ScoreA: 11, ScoreB: 5},
				},
			},
			{
				ID:         "m_f",
				Stage:      "final",
				Status:     "finished",
				TeamA:      []*player.Player{p1, p2},
				TeamB:      []*player.Player{p3, p4},
				WinnerTeam: "A",
				Sets: []event.MatchSet{
					{Number: 1, ScoreA: 11, ScoreB: 5},
				},
			},
		},
	}

	ev3 := &event.Event{
		ID:           "e3",
		Name:         "Teams Event",
		Type:         "teams",
		Format:       "elimination",
		Status:       "finished",
		Participants: []*player.Player{p1, p2, p3, p4},
		Matches: []event.Match{
			{
				ID:         "m_team_final",
				Stage:      "final",
				Status:     "finished",
				TeamA:      []*player.Player{p1, p2},
				TeamB:      []*player.Player{p3, p4},
				WinnerTeam: "A",
			},
		},
	}

	tourn := &tournament.Tournament{
		ID:     "t1",
		Name:   "Grand Tournament",
		Events: []*event.Event{ev1, ev2, ev3},
	}

	pdfBytes, err := gen.GenerateEventReport(tourn, nil)
	if err != nil {
		t.Fatalf("unexpected error generating event report: %v", err)
	}

	if len(pdfBytes) == 0 {
		t.Fatal("expected non-empty byte slice for PDF report")
	}

	if !bytes.HasPrefix(pdfBytes, []byte("%PDF")) {
		t.Error("expected generated bytes to start with %PDF header")
	}
}

func TestGoFpdfGenerator_GenerateTournamentReport_FullBracket(t *testing.T) {
	gen := pdf.NewGoFpdfGenerator()

	pA1 := &player.Player{ID: "pA1", FirstName: "A1", LastName: "Alpha", Gender: "M", SinglesElo: 1600}
	pA2 := &player.Player{ID: "pA2", FirstName: "A2", LastName: "Alpha", Gender: "M", SinglesElo: 1500}
	pA3 := &player.Player{ID: "pA3", FirstName: "A3", LastName: "Alpha", Gender: "M", SinglesElo: 1400}
	pB1 := &player.Player{ID: "pB1", FirstName: "B1", LastName: "Beta", Gender: "M", SinglesElo: 1550}
	pB2 := &player.Player{ID: "pB2", FirstName: "B2", LastName: "Beta", Gender: "M", SinglesElo: 1450}
	pB3 := &player.Player{ID: "pB3", FirstName: "B3", LastName: "Beta", Gender: "M", SinglesElo: 1350}

	win3 := []event.MatchSet{{Number: 1, ScoreA: 11, ScoreB: 5}, {Number: 2, ScoreA: 11, ScoreB: 5}, {Number: 3, ScoreA: 11, ScoreB: 5}}

	groupMatches := []event.Match{
		{ID: "gA1", Stage: "group", Status: "finished", WinnerTeam: "A", TeamA: []*player.Player{pA1}, TeamB: []*player.Player{pA2}, Sets: win3},
		{ID: "gA2", Stage: "group", Status: "finished", WinnerTeam: "A", TeamA: []*player.Player{pA1}, TeamB: []*player.Player{pA3}, Sets: win3},
		{ID: "gA3", Stage: "group", Status: "finished", WinnerTeam: "A", TeamA: []*player.Player{pA2}, TeamB: []*player.Player{pA3}, Sets: win3},
		{ID: "gB1", Stage: "group", Status: "finished", WinnerTeam: "A", TeamA: []*player.Player{pB1}, TeamB: []*player.Player{pB2}, Sets: win3},
		{ID: "gB2", Stage: "group", Status: "finished", WinnerTeam: "A", TeamA: []*player.Player{pB1}, TeamB: []*player.Player{pB3}, Sets: win3},
		{ID: "gB3", Stage: "group", Status: "finished", WinnerTeam: "A", TeamA: []*player.Player{pB2}, TeamB: []*player.Player{pB3}, Sets: win3},
	}

	// Knockout seeds resolve (per getITTFKnockoutSeeds) to [pA1, pB1, pA2, pB2],
	// paired via the standard bracket arrangement as (pA1 vs pB2) and (pA2 vs pB1).
	tableNum := 3
	updated := time.Now()
	knockoutMatches := []event.Match{
		{ID: "sf1", Stage: "semifinal", Status: "finished", WinnerTeam: "A", TeamA: []*player.Player{pA1}, TeamB: []*player.Player{pB2}, TableNumber: &tableNum, UpdatedAt: &updated, Sets: win3},
		{ID: "sf2", Stage: "semifinal", Status: "finished", WinnerTeam: "A", TeamA: []*player.Player{pA2}, TeamB: []*player.Player{pB1}, Sets: win3},
		{ID: "final1", Stage: "final", Status: "finished", DivisionID: "div1", WinnerTeam: "A", TeamA: []*player.Player{pA1}, TeamB: []*player.Player{pA2}, Sets: win3},
	}

	var allMatches []event.Match
	allMatches = append(allMatches, groupMatches...)
	allMatches = append(allMatches, knockoutMatches...)

	maxElo := int16(1700)
	divs := []*division.Division{
		{ID: "div1", Name: "Elite Division", MinElo: 1000, MaxElo: &maxElo, Category: "singles"},
		{ID: "div-mismatch", Name: "Doubles Only", MinElo: 0, MaxElo: nil, Category: "doubles"},
		{ID: "div-skip", Name: "No Division", MinElo: 0, MaxElo: nil, Category: "both"},
	}

	ev := &event.Event{
		ID:             "e1",
		Name:           "Full Bracket Championship",
		Type:           "singles",
		Format:         "groups_elimination",
		Status:         "finished",
		StartDate:      time.Now(),
		GroupPassCount: 2,
		Participants:   []*player.Player{pA1, pA2, pA3, pB1, pB2, pB3},
		Groups: []event.Group{
			{ID: "gA", Name: "Elite - Group A", Players: []*player.Player{pA1, pA2, pA3}},
			{ID: "gB", Name: "Elite - Group B", Players: []*player.Player{pB1, pB2, pB3}},
		},
		Matches: allMatches,
		Metrics: &event.TournamentMetrics{
			TotalMatchesPlayed:    9,
			TotalSetsPlayed:       27,
			TotalPointsScored:     500,
			AveragePointsPerMatch: 55.5,
			AverageSetsPerMatch:   3,
			CleanSweeps:           9,
			AverageEloAtStart:     1500,
			DivisionMetrics: map[string]event.DivisionMetric{
				"div1":    {TotalMatchesPlayed: 3, AveragePointsPerMatch: 55},
				"default": {TotalMatchesPlayed: 6, AveragePointsPerMatch: 56},
			},
		},
	}

	pdfBytes, err := gen.GenerateTournamentReport(ev, divs)
	if err != nil {
		t.Fatalf("unexpected error generating tournament report: %v", err)
	}
	if len(pdfBytes) == 0 {
		t.Fatal("expected non-empty byte slice for PDF report")
	}
	if !bytes.HasPrefix(pdfBytes, []byte("%PDF")) {
		t.Error("expected generated bytes to start with %PDF header")
	}
}

func TestGetDivisionPlaces(t *testing.T) {
	p1 := &player.Player{ID: "p1", FirstName: "Winner", LastName: "User"}
	p2 := &player.Player{ID: "p2", FirstName: "Runner", LastName: "Up"}
	p3 := &player.Player{ID: "p3", FirstName: "Semi", LastName: "Finalist"}

	ev := &event.Event{
		Status: "finished",
		Format: "elimination",
		Type:   "singles",
		Matches: []event.Match{
			{
				Stage:      "final",
				Status:     "finished",
				DivisionID: "div1",
				TeamA:      []*player.Player{p1},
				TeamB:      []*player.Player{p2},
				WinnerTeam: "A",
			},
			{
				Stage:      "semifinal",
				Status:     "finished",
				DivisionID: "div1",
				TeamA:      []*player.Player{p2},
				TeamB:      []*player.Player{p3},
				WinnerTeam: "A",
			},
		},
	}

	first, second, third := pdf.GetDivisionPlaces(ev, "div1", []*player.Player{p1, p2, p3})
	if first == "" || second == "" {
		t.Errorf("expected non-empty 1st and 2nd places, got first=%q, second=%q", first, second)
	}
	if third == "" {
		t.Errorf("expected non-empty 3rd place, got %q", third)
	}
}

func TestGetDivisionPlaces_NotFinished(t *testing.T) {
	ev := &event.Event{Status: "in_progress"}
	first, second, third := pdf.GetDivisionPlaces(ev, "div1", nil)
	if first != "" || second != "" || third != "" {
		t.Errorf("expected empty places for unfinished event, got %q/%q/%q", first, second, third)
	}
}

func TestGetDivisionPlaces_WinnerBBranch(t *testing.T) {
	p1 := &player.Player{ID: "p1", FirstName: "Winner", LastName: "User"}
	p2 := &player.Player{ID: "p2", FirstName: "Runner", LastName: "Up"}
	p3 := &player.Player{ID: "p3", FirstName: "Semi", LastName: "Finalist"}
	p4 := &player.Player{ID: "p4", FirstName: "Other", LastName: "Semi"}

	ev := &event.Event{
		Status: "finished",
		Format: "elimination",
		Type:   "singles",
		Matches: []event.Match{
			{
				Stage:      "final",
				Status:     "finished",
				DivisionID: "div1",
				TeamA:      []*player.Player{p2}, // loser is TeamA this time
				TeamB:      []*player.Player{p1}, // winner is TeamB
				WinnerTeam: "B",
			},
			{
				Stage:      "semifinal",
				Status:     "finished",
				DivisionID: "div1",
				TeamA:      []*player.Player{p3},
				TeamB:      []*player.Player{p2},
				WinnerTeam: "B", // TeamA (p3) is the semifinal loser
			},
			{
				Stage:      "semifinal",
				Status:     "finished",
				DivisionID: "div1",
				TeamA:      []*player.Player{p1},
				TeamB:      []*player.Player{p4},
				WinnerTeam: "A", // TeamB (p4) is the semifinal loser
			},
		},
	}

	first, second, third := pdf.GetDivisionPlaces(ev, "div1", []*player.Player{p1, p2, p3, p4})
	if first != "Winner User" {
		t.Errorf("expected first to be Winner User, got %q", first)
	}
	if second != "Runner Up" {
		t.Errorf("expected second to be Runner Up, got %q", second)
	}
	if third == "" {
		t.Errorf("expected non-empty third place, got %q", third)
	}
}

func TestGetDivisionPlaces_RoundRobin(t *testing.T) {
	p1 := &player.Player{ID: "p1", FirstName: "First", LastName: "Place", SinglesElo: 1600}
	p2 := &player.Player{ID: "p2", FirstName: "Second", LastName: "Place", SinglesElo: 1500}
	p3 := &player.Player{ID: "p3", FirstName: "Third", LastName: "Place", SinglesElo: 1400}

	win3 := []event.MatchSet{{Number: 1, ScoreA: 11, ScoreB: 5}, {Number: 2, ScoreA: 11, ScoreB: 5}, {Number: 3, ScoreA: 11, ScoreB: 5}}

	ev := &event.Event{
		Status: "finished",
		Format: "round_robin",
		Type:   "singles",
		Matches: []event.Match{
			{Stage: "group", Status: "finished", DivisionID: "div1", WinnerTeam: "A", TeamA: []*player.Player{p1}, TeamB: []*player.Player{p2}, Sets: win3},
			{Stage: "group", Status: "finished", DivisionID: "div1", WinnerTeam: "A", TeamA: []*player.Player{p1}, TeamB: []*player.Player{p3}, Sets: win3},
			{Stage: "group", Status: "finished", DivisionID: "div1", WinnerTeam: "A", TeamA: []*player.Player{p2}, TeamB: []*player.Player{p3}, Sets: win3},
		},
	}

	first, second, third := pdf.GetDivisionPlaces(ev, "div1", []*player.Player{p1, p2, p3})
	if first != "First Place" {
		t.Errorf("expected first to be First Place, got %q", first)
	}
	if second != "Second Place" {
		t.Errorf("expected second to be Second Place, got %q", second)
	}
	if third != "Third Place" {
		t.Errorf("expected third to be Third Place, got %q", third)
	}
}

func TestGetDivisionPlaces_RoundRobin_NoPlayers(t *testing.T) {
	ev := &event.Event{Status: "finished", Format: "round_robin"}
	first, second, third := pdf.GetDivisionPlaces(ev, "div1", nil)
	if first != "" || second != "" || third != "" {
		t.Errorf("expected empty places for no division players, got %q/%q/%q", first, second, third)
	}
}
