package pdf_test

import (
	"bytes"
	"context"
	"fmt"
	"image"
	"image/jpeg"
	"strings"
	"testing"
	"time"

	"table-tennis-backend/internal/domain/division"
	"table-tennis-backend/internal/domain/event"
	"table-tennis-backend/internal/domain/player"
	"table-tennis-backend/internal/domain/tournament"
	"table-tennis-backend/internal/infrastructure/pdf"
)

func TestGoFpdfGenerator_GenerateTournamentReport(t *testing.T) {
	gen := pdf.NewGoFpdfGenerator()
	if gen == nil {
		t.Fatal("expected NewGoFpdfGenerator to return non-nil instance")
	}

	p1 := &player.Player{ID: "p1", FirstName: "John", LastName: "Doe", Gender: "M", SinglesElo: 1500}
	p2 := &player.Player{ID: "p2", FirstName: "Jane", LastName: "Smith", Gender: "F", SinglesElo: 1400}
	p3 := &player.Player{ID: "p3", FirstName: "Bob", LastName: "Johnson", Gender: "M", SinglesElo: 1300}
	p4 := &player.Player{ID: "p4", FirstName: "Alice", LastName: "Williams", Gender: "F", SinglesElo: 1200}

	maxElo1500 := int16(1500)
	div1 := &division.Division{
		ID:       "div1",
		Name:     "Division 1",
		MinElo:   1000,
		MaxElo:   &maxElo1500,
		Category: "singles",
	}

	ev := &event.Event{
		ID:           "e1",
		Name:         "Championship 2026",
		Type:         "singles",
		Format:       "groups_elimination",
		Status:       "finished",
		StartDate:    time.Now(),
		Participants: []*player.Player{p1, p2, p3, p4},
		Groups: []event.Group{
			{
				ID:      "g1",
				Name:    "Group A",
				Players: []*player.Player{p1, p2},
			},
			{
				ID:      "g2",
				Name:    "Group B",
				Players: []*player.Player{p3, p4},
			},
		},
		Matches: []event.Match{
			{
				ID:         "m1",
				Stage:      "group",
				Status:     "finished",
				TeamA:      []*player.Player{p1},
				TeamB:      []*player.Player{p2},
				WinnerTeam: "A",
				Sets: []event.MatchSet{
					{Number: 1, ScoreA: 11, ScoreB: 8},
					{Number: 2, ScoreA: 11, ScoreB: 9},
					{Number: 3, ScoreA: 11, ScoreB: 5},
				},
			},
			{
				ID:         "m2",
				Stage:      "final",
				Status:     "finished",
				DivisionID: "div1",
				TeamA:      []*player.Player{p1},
				TeamB:      []*player.Player{p3},
				WinnerTeam: "A",
				Sets: []event.MatchSet{
					{Number: 1, ScoreA: 11, ScoreB: 9},
					{Number: 2, ScoreA: 11, ScoreB: 7},
					{Number: 3, ScoreA: 11, ScoreB: 8},
				},
			},
		},
		Metrics: &event.TournamentMetrics{
			TotalMatchesPlayed: 2,
			TotalSetsPlayed:    6,
			TotalPointsScored:  100,
		},
	}

	pdfBytes, err := gen.GenerateTournamentReport(ev, []*division.Division{div1})
	if err != nil {
		t.Fatalf("unexpected error generating tournament report: %v", err)
	}

	if len(pdfBytes) == 0 {
		t.Fatal("expected non-empty byte slice for PDF report")
	}

	if !bytes.HasPrefix(pdfBytes, []byte("%PDF")) {
		t.Error("expected generated bytes to start with %PDF header")
	}
}

// TestGoFpdfGenerator_GenerateTournamentReport_LargeGroupUsesLandscape covers
// a "La Liga"-style round-robin group with enough teams that the schedule +
// cross-table matrix + points columns no longer fit an A4 portrait page's
// printable width, forcing that table onto a landscape page. A small group
// follows it to confirm the report switches back to portrait afterward
// instead of leaving every later section landscape.
func TestGoFpdfGenerator_GenerateTournamentReport_LargeGroupUsesLandscape(t *testing.T) {
	gen := pdf.NewGoFpdfGenerator()

	var bigGroup []*player.Player
	for i := 0; i < 8; i++ {
		bigGroup = append(bigGroup, &player.Player{
			ID: fmt.Sprintf("big%d", i), FirstName: fmt.Sprintf("Player%d", i), LastName: "Liga", Gender: "M", SinglesElo: 1400,
		})
	}
	p1 := &player.Player{ID: "small1", FirstName: "Small", LastName: "One", Gender: "M", SinglesElo: 1400}
	p2 := &player.Player{ID: "small2", FirstName: "Small", LastName: "Two", Gender: "M", SinglesElo: 1400}

	participants := append([]*player.Player{}, bigGroup...)
	participants = append(participants, p1, p2)

	ev := &event.Event{
		ID: "e1", Name: "La Liga 2026", Type: "singles", Format: "round_robin", Status: "in_progress",
		StartDate: time.Now(), Participants: participants,
		Groups: []event.Group{
			{ID: "g1", Name: "Liga - Grupo Unico", Players: bigGroup},
			{ID: "g2", Name: "Liga - Grupo Chico", Players: []*player.Player{p1, p2}},
		},
	}

	pdfBytes, err := gen.GenerateTournamentReport(ev, nil)
	if err != nil {
		t.Fatalf("unexpected error generating tournament report: %v", err)
	}
	if !bytes.HasPrefix(pdfBytes, []byte("%PDF")) {
		t.Error("expected generated bytes to start with %PDF header")
	}
	// A landscape A4 page's MediaBox is width-major (841.89 x 595.28 pt),
	// the reverse of the portrait default (595.28 x 841.89 pt).
	if !bytes.Contains(pdfBytes, []byte("/MediaBox [0 0 841.89 595.28]")) {
		t.Error("expected the large group's table to render on a landscape page")
	}
}

// TestGoFpdfGenerator_GenerateTournamentReport_HugeGroupShrinksColumns covers
// a group large enough (23 teams, matching a real "La Liga" report) that even
// a landscape page's default column width pushes the trailing Sets/Points/Pos
// columns off the page edge. The generator must shrink the matrix column
// width until the whole table - matrix and trailer columns alike - fits.
func TestGoFpdfGenerator_GenerateTournamentReport_HugeGroupShrinksColumns(t *testing.T) {
	gen := pdf.NewGoFpdfGenerator()

	var hugeGroup []*player.Player
	for i := 0; i < 23; i++ {
		hugeGroup = append(hugeGroup, &player.Player{
			ID: fmt.Sprintf("huge%d", i), FirstName: fmt.Sprintf("Player%d", i), LastName: "Liga", Gender: "M", SinglesElo: 1400,
		})
	}

	ev := &event.Event{
		ID: "e1", Name: "La Liga 2026", Type: "singles", Format: "round_robin", Status: "in_progress",
		StartDate: time.Now(), Participants: hugeGroup,
		Groups: []event.Group{
			{ID: "g1", Name: "Open Division - All Against All", Players: hugeGroup},
		},
	}

	pdfBytes, err := gen.GenerateTournamentReport(ev, nil)
	if err != nil {
		t.Fatalf("unexpected error generating tournament report: %v", err)
	}
	if !bytes.HasPrefix(pdfBytes, []byte("%PDF")) {
		t.Error("expected generated bytes to start with %PDF header")
	}
	if !bytes.Contains(pdfBytes, []byte("/MediaBox [0 0 841.89 595.28]")) {
		t.Error("expected the huge group's table to render on a landscape page")
	}
}

func TestGoFpdfGenerator_GenerateEventReport(t *testing.T) {
	gen := pdf.NewGoFpdfGenerator()

	p1 := &player.Player{ID: "p1", FirstName: "Player", LastName: "One", Gender: "M", SinglesElo: 1500}
	p2 := &player.Player{ID: "p2", FirstName: "Player", LastName: "Two", Gender: "M", SinglesElo: 1400}
	p3 := &player.Player{ID: "p3", FirstName: "Player", LastName: "Three", Gender: "M", SinglesElo: 1400}
	p4 := &player.Player{ID: "p4", FirstName: "Player", LastName: "Four", Gender: "M", SinglesElo: 1400}

	ev1 := &event.Event{
		ID:           "e1",
		Name:         "Sub Event 1",
		Type:         "singles",
		Format:       "round_robin",
		Status:       "finished",
		Participants: []*player.Player{p1, p2},
	}

	ev2 := &event.Event{
		ID:           "e2",
		Name:         "Elimination Event",
		Type:         "doubles",
		Format:       "elimination",
		Status:       "finished",
		Participants: []*player.Player{p1, p2, p3, p4},
		Matches: []event.Match{
			{
				ID:         "m_r32",
				Stage:      "r32",
				Status:     "finished",
				TeamA:      []*player.Player{p1, p2},
				TeamB:      []*player.Player{p3, p4},
				WinnerTeam: "A",
				Sets: []event.MatchSet{
					{Number: 1, ScoreA: 11, ScoreB: 5},
				},
			},
			{
				ID:         "m_r16",
				Stage:      "r16",
				Status:     "finished",
				TeamA:      []*player.Player{p1, p2},
				TeamB:      []*player.Player{p3, p4},
				WinnerTeam: "B",
				Sets: []event.MatchSet{
					{Number: 1, ScoreA: 11, ScoreB: 5},
				},
			},
			{
				ID:         "m_qf",
				Stage:      "quarterfinal",
				Status:     "finished",
				TeamA:      []*player.Player{p1, p2},
				TeamB:      []*player.Player{p3, p4},
				WinnerTeam: "A",
				Sets: []event.MatchSet{
					{Number: 1, ScoreA: 11, ScoreB: 5},
				},
			},
			{
				ID:         "m_sf",
				Stage:      "semifinal",
				Status:     "finished",
				TeamA:      []*player.Player{p1, p2},
				TeamB:      []*player.Player{p3, p4},
				WinnerTeam: "A",
				Sets: []event.MatchSet{
					{Number: 1, ScoreA: 11, ScoreB: 5},
				},
			},
			{
				ID:         "m_f",
				Stage:      "final",
				Status:     "finished",
				TeamA:      []*player.Player{p1, p2},
				TeamB:      []*player.Player{p3, p4},
				WinnerTeam: "A",
				Sets: []event.MatchSet{
					{Number: 1, ScoreA: 11, ScoreB: 5},
				},
			},
		},
	}

	ev3 := &event.Event{
		ID:           "e3",
		Name:         "Teams Event",
		Type:         "teams",
		Format:       "elimination",
		Status:       "finished",
		Participants: []*player.Player{p1, p2, p3, p4},
		Matches: []event.Match{
			{
				ID:         "m_team_final",
				Stage:      "final",
				Status:     "finished",
				TeamA:      []*player.Player{p1, p2},
				TeamB:      []*player.Player{p3, p4},
				WinnerTeam: "A",
			},
		},
	}

	tourn := &tournament.Tournament{
		ID:     "t1",
		Name:   "Grand Tournament",
		Events: []*event.Event{ev1, ev2, ev3},
	}

	pdfBytes, err := gen.GenerateEventReport(tourn, nil, false)
	if err != nil {
		t.Fatalf("unexpected error generating event report: %v", err)
	}

	if len(pdfBytes) == 0 {
		t.Fatal("expected non-empty byte slice for PDF report")
	}

	if !bytes.HasPrefix(pdfBytes, []byte("%PDF")) {
		t.Error("expected generated bytes to start with %PDF header")
	}
}

// mockPhotoDownloader returns a tiny valid JPEG for any path containing
// "front"/"back", an error for a path containing "broken", and otherwise
// fails the test if called unexpectedly.
type mockPhotoDownloader struct {
	t        *testing.T
	fetched  []string
	jpegData []byte
}

func newMockPhotoDownloader(t *testing.T) *mockPhotoDownloader {
	var buf bytes.Buffer
	img := image.NewRGBA(image.Rect(0, 0, 2, 2))
	if err := jpeg.Encode(&buf, img, nil); err != nil {
		t.Fatalf("failed to encode fixture JPEG: %v", err)
	}
	return &mockPhotoDownloader{t: t, jpegData: buf.Bytes()}
}

func (m *mockPhotoDownloader) Download(ctx context.Context, path string) ([]byte, error) {
	m.fetched = append(m.fetched, path)
	if strings.Contains(path, "broken") {
		return nil, fmt.Errorf("simulated download failure")
	}
	return m.jpegData, nil
}

func TestGoFpdfGenerator_GenerateEventReport_AppendsIDPhotos(t *testing.T) {
	downloader := newMockPhotoDownloader(t)
	gen := pdf.NewGoFpdfGenerator().WithPhotoDownloader(downloader)

	p1 := &player.Player{ID: "p1", FirstName: "Player", LastName: "One", Gender: "M", SinglesElo: 1500,
		NationalID: "001-123456-0001A", IDFrontPath: "id_front/p1.jpg", IDBackPath: "id_back/p1.jpg"}
	// p2 has no ID photos on file -- should be skipped entirely.
	p2 := &player.Player{ID: "p2", FirstName: "Player", LastName: "Two", Gender: "M", SinglesElo: 1400}
	// p3 has an unsupported extension (webp) that fpdf can't decode.
	p3 := &player.Player{ID: "p3", FirstName: "Player", LastName: "Three", Gender: "M", SinglesElo: 1400, IDFrontPath: "id_front/p3.webp"}
	// p4's download fails.
	p4 := &player.Player{ID: "p4", FirstName: "Player", LastName: "Four", Gender: "M", SinglesElo: 1400, IDFrontPath: "id_front/broken.jpg"}

	ev1 := &event.Event{
		ID: "e1", Name: "Sub Event 1", Type: "singles", Format: "round_robin", Status: "finished",
		Participants: []*player.Player{p1, p2, p3, p4},
	}

	tourn := &tournament.Tournament{ID: "t1", Name: "Grand Tournament", Events: []*event.Event{ev1}}

	pdfBytes, err := gen.GenerateEventReport(tourn, nil, true)
	if err != nil {
		t.Fatalf("unexpected error generating event report: %v", err)
	}
	if !bytes.HasPrefix(pdfBytes, []byte("%PDF")) {
		t.Error("expected generated bytes to start with %PDF header")
	}
	if len(downloader.fetched) != 3 {
		t.Errorf("expected 3 download attempts (p1 front+back, p4 front; p2 has none, p3's webp is skipped before download), got %d: %v", len(downloader.fetched), downloader.fetched)
	}
}

func TestGoFpdfGenerator_GenerateEventReport_IDPhotosOptedOut(t *testing.T) {
	downloader := newMockPhotoDownloader(t)
	gen := pdf.NewGoFpdfGenerator().WithPhotoDownloader(downloader)

	p1 := &player.Player{ID: "p1", FirstName: "Player", LastName: "One", Gender: "M", SinglesElo: 1500, IDFrontPath: "id_front/p1.jpg"}
	ev1 := &event.Event{ID: "e1", Name: "Sub Event 1", Type: "singles", Format: "round_robin", Status: "finished", Participants: []*player.Player{p1}}
	tourn := &tournament.Tournament{ID: "t1", Name: "Grand Tournament", Events: []*event.Event{ev1}}

	// includeIDPhotos=false: even with a downloader configured and a player
	// who has a photo on file, no download should happen -- the tournament
	// didn't opt in.
	pdfBytes, err := gen.GenerateEventReport(tourn, nil, false)
	if err != nil {
		t.Fatalf("unexpected error generating event report: %v", err)
	}
	if !bytes.HasPrefix(pdfBytes, []byte("%PDF")) {
		t.Error("expected generated bytes to start with %PDF header")
	}
	if len(downloader.fetched) != 0 {
		t.Errorf("expected no download attempts when opted out, got %d: %v", len(downloader.fetched), downloader.fetched)
	}
}

func TestGoFpdfGenerator_GenerateEventReport_NoPhotoDownloaderConfigured(t *testing.T) {
	gen := pdf.NewGoFpdfGenerator() // no WithPhotoDownloader call

	p1 := &player.Player{ID: "p1", FirstName: "Player", LastName: "One", Gender: "M", SinglesElo: 1500, IDFrontPath: "id_front/p1.jpg"}
	ev1 := &event.Event{ID: "e1", Name: "Sub Event 1", Type: "singles", Format: "round_robin", Status: "finished", Participants: []*player.Player{p1}}
	tourn := &tournament.Tournament{ID: "t1", Name: "Grand Tournament", Events: []*event.Event{ev1}}

	pdfBytes, err := gen.GenerateEventReport(tourn, nil, false)
	if err != nil {
		t.Fatalf("unexpected error generating event report: %v", err)
	}
	if !bytes.HasPrefix(pdfBytes, []byte("%PDF")) {
		t.Error("expected generated bytes to start with %PDF header")
	}
}

// TestGoFpdfGenerator_GenerateTournamentReport_PlayerStatsGetsOwnPage guards
// against a regression where the player-statistics section (which draws with
// flowing CellFormat calls) continued on whatever page the bracket section
// (which draws with absolute coordinates and never advances fpdf's page/
// cursor state) left the cursor on — including a still-open landscape
// bracket page when the optional Metrics section was skipped, causing the
// stats table to render on top of the bracket.
func TestGoFpdfGenerator_GenerateTournamentReport_PlayerStatsGetsOwnPage(t *testing.T) {
	gen := pdf.NewGoFpdfGenerator()

	pA1 := &player.Player{ID: "pA1", FirstName: "A1", LastName: "Alpha", Gender: "M", SinglesElo: 1600}
	pA2 := &player.Player{ID: "pA2", FirstName: "A2", LastName: "Alpha", Gender: "M", SinglesElo: 1500}
	win3 := []event.MatchSet{{Number: 1, ScoreA: 11, ScoreB: 5}}
	matches := []event.Match{
		{ID: "final1", Stage: "final", Status: "finished", DivisionID: "div1", WinnerTeam: "A", TeamA: []*player.Player{pA1}, TeamB: []*player.Player{pA2}, Sets: win3},
	}
	maxElo := int16(1700)
	divs := []*division.Division{{ID: "div1", Name: "Elite", MinElo: 1000, MaxElo: &maxElo, Category: "singles"}}
	ev := &event.Event{
		ID: "e1", Name: "Bracket No Metrics", Type: "singles", Format: "elimination", Status: "finished",
		StartDate: time.Now(), Participants: []*player.Player{pA1, pA2},
		Groups:  []event.Group{{ID: "g1", Name: "Elite - Bracket Draw", Players: []*player.Player{pA1, pA2}}},
		Matches: matches,
		Metrics: nil, // deliberately omitted: this is the case that used to skip the page break
	}

	pdfBytes, err := gen.GenerateTournamentReport(ev, divs)
	if err != nil {
		t.Fatalf("unexpected error generating tournament report: %v", err)
	}

	// The bracket landscape page and the player-stats portrait page must be
	// distinct pages. Page object dictionaries aren't stream-compressed, so
	// counting "/Type /Page" occurrences reliably counts generated pages.
	pageCount := bytes.Count(pdfBytes, []byte("/Type /Page"))
	if pageCount < 3 {
		t.Errorf("expected at least 3 pages (cover/standings, bracket, player stats), got %d", pageCount)
	}
}

func TestGoFpdfGenerator_GenerateTournamentReport_FullBracket(t *testing.T) {
	gen := pdf.NewGoFpdfGenerator()

	pA1 := &player.Player{ID: "pA1", FirstName: "A1", LastName: "Alpha", Gender: "M", SinglesElo: 1600}
	pA2 := &player.Player{ID: "pA2", FirstName: "A2", LastName: "Alpha", Gender: "M", SinglesElo: 1500}
	pA3 := &player.Player{ID: "pA3", FirstName: "A3", LastName: "Alpha", Gender: "M", SinglesElo: 1400}
	pB1 := &player.Player{ID: "pB1", FirstName: "B1", LastName: "Beta", Gender: "M", SinglesElo: 1550}
	pB2 := &player.Player{ID: "pB2", FirstName: "B2", LastName: "Beta", Gender: "M", SinglesElo: 1450}
	pB3 := &player.Player{ID: "pB3", FirstName: "B3", LastName: "Beta", Gender: "M", SinglesElo: 1350}

	win3 := []event.MatchSet{{Number: 1, ScoreA: 11, ScoreB: 5}, {Number: 2, ScoreA: 11, ScoreB: 5}, {Number: 3, ScoreA: 11, ScoreB: 5}}

	groupMatches := []event.Match{
		{ID: "gA1", Stage: "group", Status: "finished", WinnerTeam: "A", TeamA: []*player.Player{pA1}, TeamB: []*player.Player{pA2}, Sets: win3},
		{ID: "gA2", Stage: "group", Status: "finished", WinnerTeam: "A", TeamA: []*player.Player{pA1}, TeamB: []*player.Player{pA3}, Sets: win3},
		{ID: "gA3", Stage: "group", Status: "finished", WinnerTeam: "A", TeamA: []*player.Player{pA2}, TeamB: []*player.Player{pA3}, Sets: win3},
		{ID: "gB1", Stage: "group", Status: "finished", WinnerTeam: "A", IsForfeit: true, TeamA: []*player.Player{pB1}, TeamB: []*player.Player{pB2}},
		{ID: "gB2", Stage: "group", Status: "finished", WinnerTeam: "A", TeamA: []*player.Player{pB1}, TeamB: []*player.Player{pB3}, Sets: win3},
		{ID: "gB3", Stage: "group", Status: "finished", WinnerTeam: "A", TeamA: []*player.Player{pB2}, TeamB: []*player.Player{pB3}, Sets: win3},
	}

	// Knockout seeds resolve (per getITTFKnockoutSeeds) to [pA1, pB1, pA2, pB2],
	// paired via the standard bracket arrangement as (pA1 vs pB2) and (pA2 vs pB1).
	tableNum := 3
	updated := time.Now()
	knockoutMatches := []event.Match{
		{ID: "sf1", Stage: "semifinal", Status: "finished", DivisionID: "div1", WinnerTeam: "A", IsForfeit: true, TeamA: []*player.Player{pA1}, TeamB: []*player.Player{pB2}, TableNumber: &tableNum, UpdatedAt: &updated},
		{ID: "sf2", Stage: "semifinal", Status: "finished", DivisionID: "div1", WinnerTeam: "A", TeamA: []*player.Player{pA2}, TeamB: []*player.Player{pB1}, Sets: win3},
		{ID: "final1", Stage: "final", Status: "finished", DivisionID: "div1", WinnerTeam: "A", TeamA: []*player.Player{pA1}, TeamB: []*player.Player{pA2}, Sets: win3},
	}

	var allMatches []event.Match
	allMatches = append(allMatches, groupMatches...)
	allMatches = append(allMatches, knockoutMatches...)

	maxElo := int16(1700)
	divs := []*division.Division{
		{ID: "div1", Name: "Elite Division", MinElo: 1000, MaxElo: &maxElo, Category: "singles"},
		{ID: "div-mismatch", Name: "Doubles Only", MinElo: 0, MaxElo: nil, Category: "doubles"},
		{ID: "div-skip", Name: "No Division", MinElo: 0, MaxElo: nil, Category: "both"},
	}

	ev := &event.Event{
		ID:             "e1",
		Name:           "Full Bracket Championship",
		Type:           "singles",
		Format:         "groups_elimination",
		Status:         "finished",
		StartDate:      time.Now(),
		GroupPassCount: 2,
		Participants:   []*player.Player{pA1, pA2, pA3, pB1, pB2, pB3},
		Groups: []event.Group{
			{ID: "gA", Name: "Elite - Group A", Players: []*player.Player{pA1, pA2, pA3}},
			{ID: "gB", Name: "Elite - Group B", Players: []*player.Player{pB1, pB2, pB3}},
		},
		Matches: allMatches,
		Metrics: &event.TournamentMetrics{
			TotalMatchesPlayed:    9,
			TotalSetsPlayed:       27,
			TotalPointsScored:     500,
			AveragePointsPerMatch: 55.5,
			AverageSetsPerMatch:   3,
			CleanSweeps:           9,
			AverageEloAtStart:     1500,
			DivisionMetrics: map[string]event.DivisionMetric{
				"div1":    {TotalMatchesPlayed: 3, AveragePointsPerMatch: 55},
				"default": {TotalMatchesPlayed: 6, AveragePointsPerMatch: 56},
			},
		},
	}

	pdfBytes, err := gen.GenerateTournamentReport(ev, divs)
	if err != nil {
		t.Fatalf("unexpected error generating tournament report: %v", err)
	}
	if len(pdfBytes) == 0 {
		t.Fatal("expected non-empty byte slice for PDF report")
	}
	if !bytes.HasPrefix(pdfBytes, []byte("%PDF")) {
		t.Error("expected generated bytes to start with %PDF header")
	}
}

func TestGetDivisionPlaces(t *testing.T) {
	p1 := &player.Player{ID: "p1", FirstName: "Winner", LastName: "User"}
	p2 := &player.Player{ID: "p2", FirstName: "Runner", LastName: "Up"}
	p3 := &player.Player{ID: "p3", FirstName: "Semi", LastName: "Finalist"}

	ev := &event.Event{
		Status: "finished",
		Format: "elimination",
		Type:   "singles",
		Matches: []event.Match{
			{
				Stage:      "final",
				Status:     "finished",
				DivisionID: "div1",
				TeamA:      []*player.Player{p1},
				TeamB:      []*player.Player{p2},
				WinnerTeam: "A",
			},
			{
				Stage:      "semifinal",
				Status:     "finished",
				DivisionID: "div1",
				TeamA:      []*player.Player{p2},
				TeamB:      []*player.Player{p3},
				WinnerTeam: "A",
			},
		},
	}

	first, second, third := pdf.GetDivisionPlaces(ev, "div1", []*player.Player{p1, p2, p3})
	if first == "" || second == "" {
		t.Errorf("expected non-empty 1st and 2nd places, got first=%q, second=%q", first, second)
	}
	if third == "" {
		t.Errorf("expected non-empty 3rd place, got %q", third)
	}
}

func TestGetDivisionPlaces_NotFinished(t *testing.T) {
	ev := &event.Event{Status: "in_progress"}
	first, second, third := pdf.GetDivisionPlaces(ev, "div1", nil)
	if first != "" || second != "" || third != "" {
		t.Errorf("expected empty places for unfinished event, got %q/%q/%q", first, second, third)
	}
}

func TestGetDivisionPlaces_WinnerBBranch(t *testing.T) {
	p1 := &player.Player{ID: "p1", FirstName: "Winner", LastName: "User"}
	p2 := &player.Player{ID: "p2", FirstName: "Runner", LastName: "Up"}
	p3 := &player.Player{ID: "p3", FirstName: "Semi", LastName: "Finalist"}
	p4 := &player.Player{ID: "p4", FirstName: "Other", LastName: "Semi"}

	ev := &event.Event{
		Status: "finished",
		Format: "elimination",
		Type:   "singles",
		Matches: []event.Match{
			{
				Stage:      "final",
				Status:     "finished",
				DivisionID: "div1",
				TeamA:      []*player.Player{p2}, // loser is TeamA this time
				TeamB:      []*player.Player{p1}, // winner is TeamB
				WinnerTeam: "B",
			},
			{
				Stage:      "semifinal",
				Status:     "finished",
				DivisionID: "div1",
				TeamA:      []*player.Player{p3},
				TeamB:      []*player.Player{p2},
				WinnerTeam: "B", // TeamA (p3) is the semifinal loser
			},
			{
				Stage:      "semifinal",
				Status:     "finished",
				DivisionID: "div1",
				TeamA:      []*player.Player{p1},
				TeamB:      []*player.Player{p4},
				WinnerTeam: "A", // TeamB (p4) is the semifinal loser
			},
		},
	}

	first, second, third := pdf.GetDivisionPlaces(ev, "div1", []*player.Player{p1, p2, p3, p4})
	if first != "Winner User" {
		t.Errorf("expected first to be Winner User, got %q", first)
	}
	if second != "Runner Up" {
		t.Errorf("expected second to be Runner Up, got %q", second)
	}
	if third == "" {
		t.Errorf("expected non-empty third place, got %q", third)
	}
}

func TestGetDivisionPlaces_RoundRobin(t *testing.T) {
	p1 := &player.Player{ID: "p1", FirstName: "First", LastName: "Place", SinglesElo: 1600}
	p2 := &player.Player{ID: "p2", FirstName: "Second", LastName: "Place", SinglesElo: 1500}
	p3 := &player.Player{ID: "p3", FirstName: "Third", LastName: "Place", SinglesElo: 1400}

	win3 := []event.MatchSet{{Number: 1, ScoreA: 11, ScoreB: 5}, {Number: 2, ScoreA: 11, ScoreB: 5}, {Number: 3, ScoreA: 11, ScoreB: 5}}

	ev := &event.Event{
		Status: "finished",
		Format: "round_robin",
		Type:   "singles",
		Matches: []event.Match{
			{Stage: "group", Status: "finished", DivisionID: "div1", WinnerTeam: "A", TeamA: []*player.Player{p1}, TeamB: []*player.Player{p2}, Sets: win3},
			{Stage: "group", Status: "finished", DivisionID: "div1", WinnerTeam: "A", TeamA: []*player.Player{p1}, TeamB: []*player.Player{p3}, Sets: win3},
			{Stage: "group", Status: "finished", DivisionID: "div1", WinnerTeam: "A", TeamA: []*player.Player{p2}, TeamB: []*player.Player{p3}, Sets: win3},
		},
	}

	first, second, third := pdf.GetDivisionPlaces(ev, "div1", []*player.Player{p1, p2, p3})
	if first != "First Place" {
		t.Errorf("expected first to be First Place, got %q", first)
	}
	if second != "Second Place" {
		t.Errorf("expected second to be Second Place, got %q", second)
	}
	if third != "Third Place" {
		t.Errorf("expected third to be Third Place, got %q", third)
	}
}

func TestGetDivisionPlaces_RoundRobin_NoPlayers(t *testing.T) {
	ev := &event.Event{Status: "finished", Format: "round_robin"}
	first, second, third := pdf.GetDivisionPlaces(ev, "div1", nil)
	if first != "" || second != "" || third != "" {
		t.Errorf("expected empty places for no division players, got %q/%q/%q", first, second, third)
	}
}
