ALTER TABLE matches ADD COLUMN IF NOT EXISTS proposed_sets JSONB;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS proposed_by_player_id UUID REFERENCES players(id) ON DELETE SET NULL;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS proposed_at TIMESTAMP;
